name: CI/CD Workflow

on:
  push:
    branches:
      - master    # Trigger workflow on push to the 'main' branch
  pull_request:
    branches:
      - master    # Trigger workflow on pull request to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3   # Fetch the code from the repository

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'        # Specify Node.js version

      - name: Install dependencies
        run: npm install            # Install project dependencies

      - name: Run tests
        run: npm test               # Run tests

  deploy:
    needs: build                   # Run this job only after the 'build' job succeeds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production
        run: echo "Deploying application..." # Replace with deployment script/commands
