name: CodeQL

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

  
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        language:
          - javascript

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          output: results.sarif

      - name: Upload SARIF as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: codeql-results
          path: results.sarif
