name: CodeQL

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

permissions:
  actions: read
  contents: read
  security-events: write  # Required for uploading SARIF results

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        language:
          - javascript

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          output: results.sarif
          category: javascript-${{ github.run_id }}  # Unique category per run

      - name: Upload CodeQL results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          category: javascript-${{ github.run_id }}
